version: '3.8'
services:
  backend:
    build: 
      context: ./blog_backend
      dockerfile: Dockerfile
    volumes:
      - ./blog_backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    depends_on:
      - db
    networks:
      - twitter_network
  frontend:
    build: ./twitter_frontend
    volumes:
      - ./twitter_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - twitter_network
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - twitter_network
    ports:
      - "5432:5432"
  # redis:
  #   image: redis
  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
networks:
  twitter_network: